version: "3.8"

services:
  strapi:
    image: ghcr.io/samnangNhum/axion-webapi:latest
    container_name: strapi
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: axion-db
      DATABASE_USERNAME: axiontrade-db
      DATABASE_PASSWORD: Axiontrade@168
      DATABASE_SSL: "false"
    volumes:
      - ./app:/srv/app # Map local project for development
      - /srv/app/node_modules # Prevent conflicts with local node_modules
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ax10nTr@d3!1G8&z
      MYSQL_DATABASE: axion-db
      MYSQL_USER: axiontrade-db
      MYSQL_PASSWORD: Axiontrade@168
    ports:
      - "3333:3306" # MySQL default port mapped to 3333 on the host
    volumes:
      - ./data:/var/lib/mysql
