name: CI/CD - Build and Push to GHCR

# Trigger the workflow on pushes to the develop branch
on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image (ensure name is lowercase)
      - name: Build Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/axion-webapi:latest
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          echo "Building image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .

      # Step 4: Push the Docker image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/axion-webapi:latest
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          echo "Pushing image: $IMAGE_NAME"
          docker push $IMAGE_NAME

      # Step 5: Optional Test - Run the image with Docker Compose
      - name: Test Docker Compose
        run: |
          docker-compose up -d
          sleep 10  # Wait for services to initialize
          docker-compose ps
          docker-compose down
